# This is a basic workflow that is manually triggered

name: Run Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Setup GHDL
      run: |
        pwd
        cat /proc/cpuinfo
        sudo apt update
        sudo apt install -y gnat
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 10
        rm llvm.sh
        cd ..
        git clone https://github.com/ghdl/ghdl.git
        cd ghdl
        git checkout v1.0.0
        ./configure --with-llvm-config=/usr/bin/llvm-config-10 --prefix=/usr/local
        sudo make -j4
        sudo make install
        cd ..
    - name: GHDL version
      run: ghdl --version
    - name: Prepare OSVVM
      run: |
        pwd
        cd ..
        git clone https://github.com/osvvm/osvvm.git
        cd osvvm
        git checkout 2020.12a
        cd ..
    - name: Clone Code
      uses: actions/checkout@v2
    - name: Build OSVVM
      run: |
        pwd
        ls -la
        git log -1
        /usr/local/lib/ghdl/vendors/compile-osvvm.sh --source /home/runner/work/randx_fpga/osvvm --all --output osvvm
    - name: Run CPU Loop Engine Tests
      run: |
        make loop_engine_tests | tee loop_engine_tests.txt
        cat loop_engine_tests.txt | grep -c -i -E "Alert|error|failed" | grep -q "^0$"
    - name: Run Scratchpad Tests
      run: |
        make scratchpad_tests | tee scratchpad_tests.txt
        cat scratchpad_tests.txt | grep -c -i -E "Alert|error|failed" | grep -q "^0$"
    - name: Run Int ALU Tests
      run: |
        make int_alu_tests | tee int_alu_tests.txt
        cat int_alu_tests.txt | grep -c -i -E "Alert|error|failed" | grep -q "^0$"
    - name: Run Float ALU Tests
      run: |
        make float_alu_tests | tee float_alu_tests.txt
        cat float_alu_tests.txt | grep -c -i -E "Alert|error|failed" | grep -q "^0$"
