# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Setup GHDL
      run: |
        pwd
        cat /proc/cpuinfo
        sudo apt update
        sudo apt install -y gnat
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 10
        rm llvm.sh
        cd ..
        git clone https://github.com/ghdl/ghdl.git
        cd ghdl
        git checkout v1.0.0
        ./configure --with-llvm-config=/usr/bin/llvm-config-10 --prefix=/usr/local
        sudo make -j4
        sudo make install
        cd ..
    - name: GHDL version
      run: ghdl --version
    - name: Prepare OSVVM
      run: |
        pwd
        cd ..
        git clone https://github.com/osvvm/osvvm.git
        cd osvvm
        git checkout 2020.12a
        cd ..
    - name: Clone Code
      uses: actions/checkout@v2
    - name: Build OSVVM
      run: |
        pwd
        ls -la
        git log -1
        declare -A InstallationDirectory[OSVVM]="/home/runner/work/randx_fpga_private/osvvm"
        /usr/local/lib/ghdl/vendors/compile-osvvm.sh --all
    - name: Run CPU Full Program Tests
      run: |
        make fullprogram_tests | tee fullprogram_tests.txt
        cat fullprogram_tests.txt | grep -c -i -E "Alert|error|failed" | grep -q "^0$"